NoseBleedSeat/urls.py
from django.contrib import admin
from django.urls import path, include
from NoseBleedSeat import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name='home'),
    path("about/", views.about, name='about'),
    path('update-league-leaders/', views.update_league_leaders, name='update_league_leaders'),
    path('show-career-awards-player1/<str:player1_name>/<str:player1_id>>', views.show_career_awards_player1, name='show_career_awards_player1'),
    path('show-career-awards-player2/<str:player2_name>/<str:player2_id>>', views.show_career_awards_player2, name='show_career_awards_player2'),
    path("stats/", include('nba_stats.urls')),
    path("nba-news/", include('nba_news.urls')),
    path("nba-today/", include('nba_today.urls')),
    path("nba-teams/", include('nba_teams.urls')),
]

nba_news/urls.py
from django.urls import path
from . import views

app_name = 'nba_news'

urlpatterns = [

    path('the-ringer/', views.the_ringer_news, name='ringer_news'),
]

nba_today/urls.py
from django.urls import path
from . import views

app_name = 'nba_today'

urlpatterns = [

    path('', views.nba_results, name='nba_results'),
    path('game-leaders/<int:num>/', views.game_leaders, name='game_leaders')
]

nba_today/models.py
from django.db import models


# # This class will store team logos in the database
# class TeamLogo(models.Model):
#     team_id = models.CharField(unique=True, max_length=50)
#     team_name = models.CharField(max_length=50)
#     team_full_name = models.CharField(max_length=50, default="N/A")
#     team_city = models.CharField(max_length=50, default="N/A")
#     logo_url = models.URLField()
#     team_colour = models.CharField(unique=False, max_length=50, default="#7E354D")
#
#     def __str__(self):
#         return f'{self.team_name}'

nba_today/views.py
from django.shortcuts import render

from nba_stats.forms import PlayerSearchForm
from .functions import get_scores, get_team_image
from nba_stats.functions import get_player_image


def nba_results(request):
    results = get_scores()

    for num, game in enumerate(results):
        # Get home teams logos
        team_id = game['homeTeam']['teamId']
        team_name = game['homeTeam']['teamTricode']
        # Get team logo
        home_logo = get_team_image(team_id, team_name)

        # save team logo and game number to results
        # Game num will be used to retrieve game leaders for each game
        game['homeTeam']['teamLogo'] = home_logo
        game['homeTeam']['gameNum'] = num

        # Get away teams logos
        team_id = game['awayTeam']['teamId']
        team_name = game['awayTeam']['teamTricode']
        # Get team logo
        away_logo = get_team_image(team_id, team_name)

        # save team logo and game number to results
        game['awayTeam']['teamLogo'] = away_logo
        game['awayTeam']['gameNum'] = num

    # search form
    player_form = PlayerSearchForm()

    context = {
        'player_form': player_form,
        'results': results
    }

    return render(request, 'nba_today/game_results.html', context=context)


def game_leaders(request, num):
    # Get requested game by index
    results = get_scores()
    my_game = results[num]

    # Get game leaders
    leaders = my_game['gameLeaders']

    # Get player ids and names
    home_player_id = leaders['homeLeaders']['personId']
    home_player_name = leaders['homeLeaders']['name']

    away_player_id = leaders['awayLeaders']['personId']
    away_player_name = leaders['awayLeaders']['name']

    # get player headshots
    home_player_image = get_player_image(home_player_id, home_player_name)
    away_player_image = get_player_image(away_player_id, away_player_name)

    # Get team names
    home_team = leaders['homeLeaders']['teamTricode']
    away_team = leaders['awayLeaders']['teamTricode']

    # Get team logos
    home_team_id = my_game['homeTeam']['teamId']
    home_team_logo = get_team_image(home_team_id, home_team)

    away_team_id = my_game['awayTeam']['teamId']
    away_team_logo = get_team_image(away_team_id, away_team)

    # Get game breakdown
    home_team_scores = my_game['homeTeam']['periods']
    home_final_score = my_game['homeTeam']['score']
    away_team_scores = my_game['awayTeam']['periods']
    away_final_score = my_game['awayTeam']['score']

    # search form
    player_form = PlayerSearchForm()

    context = {
        'player_form': player_form,
        'leaders': leaders,
        'home_player_image': home_player_image,
        'home_player_name': home_player_name,
        'away_player_name': away_player_name,
        'away_player_image': away_player_image,
        'away_player_id': away_player_id,
        'home_player_id': home_player_id,
        'home_team': home_team,
        'away_team': away_team,
        'home_team_logo': home_team_logo,
        'away_team_logo': away_team_logo,
        'home_team_scores': home_team_scores,
        'home_final_score': home_final_score,
        'away_team_scores': away_team_scores,
        'away_final_score': away_final_score
    }

    return render(request, 'nba_today/game_leaders.html', context=context)

templates/nba_today/game_leaders.html
{% extends 'base.html' %}
{% load humanize %}
{% load custom_tags %}
{% load static %}
{% block title %}
Game Leaders {{ leaders.homeLeaders.teamTricode }} vs {{ leaders.awayLeaders.teamTricode }}
{% endblock %}

{% block content %}
 <div class="container-fluid p-0">
          <div class="jumbotron jumbotron-fluid">
        <div class="container text-center">
            <img src="{{ home_team_logo }}" alt="{{ home_team_logo }} Logo" class="img-fluid w-25">
            <h2>{{ home_team }} VS {{ away_team }}</h2>
            <img src="{{ away_team_logo }}" alt="{{ away_team_logo }} Logo" class="img-fluid w-25">
        </div>

              <div class="row">
        <div class="col-md-12"> <!-- Use col-md-12 to take the full width of the container -->
            <h2 class="container text-center">Game Breakdown</h2>
            <div class="table-responsive">
                <table class="table table-bordered mt-2">
            <thead>
            <h2>{{ home_team }} Final {{ home_final_score }}</h2>
                <tr>
                    <th>Period</th>
                    <th>Period Type</th>
                    <th>Score</th>
                </tr>
            </thead>

           <tbody>
                {% for home_info in home_team_scores %}
            <tr>
                    <td>{{  home_info.period }}</td>
                    <td>{{  home_info.periodType }}</td>
                    <td>{{  home_info.score }}</td>
    </tr>
           {% endfor %}
            </tbody>
        </table>

                <table class="table table-bordered mt-2">
            <thead>
            <h2>{{ away_team }}  Final {{ away_final_score }}</h2>
                <tr>
                    <th>Period</th>
                    <th>Period Type</th>
                    <th>Score</th>
                </tr>
            </thead>

           <tbody>
           {% for away_info in away_team_scores %}
            <tr>
                    <td>{{ away_info.period }}</td>
                    <td>{{  away_info.periodType }}</td>
                    <td>{{  away_info.score }}</td>
    </tr>
           {% endfor %}
            </tbody>
        </table>
            </div>
        </div>
    </div>
          </div>
     <br><br>
        <div class="container mt-5">
            {% if home_player_image %}
            <h2 class="container text-center">Game Leaders</h2>
            <br>
    <div class="row mb-4">
        <div class="col-md-6 container text-center">
            <img src="{{ home_player_image }}" alt="{{ home_player_name }} headshot" class="img-fluid w-50">
            <p><b>{{ home_player_name }} | #{{ leaders.homeLeaders.jerseyNum }} | {{ leaders.homeLeaders.position }} | {{ leaders.homeLeaders.teamTricode }}</b></p>
            <h4>PTS {{ leaders.homeLeaders.points }}</h4>
            <h4>REBS {{ leaders.homeLeaders.rebounds }}</h4>
            <h4>ASST {{ leaders.homeLeaders.assists }}</h4>
        </div>
        <div class="col-md-6 container text-center">
            <img src="{{ away_player_image }}" alt="{{ away_player_name }} headshot" class="img-fluid w-50">
            <p><b>{{ away_player_name }} | #{{ leaders.awayLeaders.jerseyNum }} | {{ leaders.awayLeaders.position }} | {{ leaders.awayLeaders.teamTricode }}</b></p>
            <h4>PTS {{ leaders.awayLeaders.points }}</h4>
            <h4>REBS {{ leaders.awayLeaders.rebounds }}</h4>
            <h4>ASST {{ leaders.awayLeaders.assists }}</h4>
        </div>
    </div>
             <a class="btn btn-primary btn-sm" href="{% url 'nba_today:nba_results' %}" role="button">Back To Game Results</a>
            <hr>
            {% else %}
            <h2>This Game Has Not Been Played Yet</h2>
            {% endif %}
</div>
 </div>
     <br><br>
{% endblock %}

templates/nba_today/game_results.html
{% extends 'base.html' %}
{% load humanize %}
{% load custom_tags %}
{% load static %}
{% block title %}
NBA Games Today
{% endblock %}

{% block content %}
 <div class="container-fluid p-0">
          <div class="jumbotron jumbotron-fluid">
        <div class="container text-center">
            <h2>Today's NBA Games</h2>
        </div>
          </div>
     <br>
        <div class="container mt-5">
            {% if results %}
                {% for game in results %}
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <img src="{{ game.homeTeam.teamLogo }}" alt="{{ game.homeTeam.teamTricode }} Logo" class="img-fluid w-25">
                            <h4>{{ game.homeTeam.teamCity }} {{ game.homeTeam.teamName }}</h4>
                             <h4>{{ game.homeTeam.wins }} - {{ game.homeTeam.losses }}</h4>
                            <h4>SCORE: {{ game.homeTeam.score }}</h4>
                        </div>
                        <div class="col-md-6">
                            <img src="{{ game.awayTeam.teamLogo }}" alt="{{ game.awayTeam.teamTricode }} Logo" class="img-fluid w-25">
                            <h4>{{ game.awayTeam.teamCity }} {{ game.awayTeam.teamName }}</h4>
                            <h4>{{ game.awayTeam.wins }} - {{ game.awayTeam.losses }}</h4>
                            <h4>SCORE: {{ game.awayTeam.score }}</h4>
                        </div>
                    </div>
                    <a class="btn btn-primary btn-sm" href="{% url 'nba_today:game_leaders' num=game.homeTeam.gameNum %}" role="button">View Game Details</a>
                    <hr>
                {% endfor %}
            {% else %}
                <h2>There Were No Games Played Last Night</h2>
            {% endif %}
</div>
 </div>
     <br><br>
{% endblock %}